### ISSUE TITLE
What is Y-axis in this chart?

### ISSUE THREAD

**Issue by HidetakaKo** [rkipp1210/data-projects#2]
Hi Ross,

I enjoyed your blog post on the iPhone step data. Good stuff! 

By the way, I have a question about your blog. What is Y-axis in this chart?

![screen shot 2016-09-09 at 18 43 32](https://cloud.githubusercontent.com/assets/13757620/18407223/66b551d8-76bf-11e6-8979-ee344100a6d3.png)

**Comment by rosskipp** [comment]
Hey!

Glad you enjoyed the blog post! :smile:

This is a density plot - the ggplot docs say `Gaussian kernel density estimation for distribution of x parameter`. So the Y values are the densities or likelihoods of the x parameter, in this case steps, at a given value. An alternative to this could have been two histograms to show the distribution differences, but I thought the lines would be easier to differentiate.

Here's some more info if you want to read more:
https://en.wikipedia.org/wiki/Probability_density_function
https://en.wikipedia.org/wiki/Kernel_density_estimation
