### ISSUE TITLE
Weekend days in iPhone data

### ISSUE THREAD

**Issue by bobhaffner** [rkipp1210/data-projects#3]
Hi Ross,  

I enjoyed your blog post on the iphone step data.   Good stuff!  Hey quick fyi on determining weekend days.  

Instead of applying that helper function you could do the following
df_daily['weekend'] = df_daily.index.weekday > 4

Bob

**Comment by rosskipp** [comment]
Hey Bob,

Glad you enjoyed the post! Thanks for the tip - that looks a lot more elegant than my function :smile: 

Ross
